# Site settings
title: "Teguh Suandi"
email: mteguhasuandi@gmail.com
description: "Not only about coding."
baseurl: ""
url: "http://mtasuandi.com/"
title_description: "I try to track everything here, not only about coding but also stories."
title_image: "https://avatars0.githubusercontent.com/u/2455314?v=3&s=460"
google_analytics: "UA-20365477-4"
disqus_account: mtasuandi
github_repository: https://github.com/mtasuandi/mtasuandi.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: mtasuandi
github_username: mtasuandi
linkedin_link: https://id.linkedin.com/in/mtasuandi
google_plus_link: https://plus.google.com/u/2/109088390701176899804
stackoverflow_link: http://mtasuandi.com/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/mtasuandi\">Teguh Suandi</a>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
